name: Run CI checks

on: [pull_request]

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

jobs:
  all:
    runs-on: ubuntu-latest
    name: Building affected apps
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.7.9
      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=build --base=origin/master --parallel
      - run: npx nx affected --target=test --base=origin/master --parallel
      - run: npx nx affected --target=lint --base=origin/master --parallel
      - run: npx nx affected --target=e2e --base=origin/master --parallel
      - run: npx nx-cloud stop-all-agents
  agents:
    runs-on: ubuntu-latest
    name: Agent 1
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [ 1, 2, 3, 4 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
